// O'zbekiston viloyatlari va tumanlari (soddalashtirilgan ro'yxat).
// Xarita ishlatilmaydi — foydalanuvchi shu ro'yxatdan select qiladi.

export interface Region {
  name: string;
  districts: string[];
}

export const REGIONS: Region[] = [
  {
    name: "Toshkent shahri",
    districts: [
      "Bektemir",
      "Chilonzor",
      "Mirobod",
      "Mirzo Ulug'bek",
      "Sergeli",
      "Shayxontohur",
      "Olmazor",
      "Uchtepa",
      "Yakkasaroy",
      "Yashnobod",
      "Yunusobod",
    ],
  },
  {
    name: "Toshkent viloyati",
    districts: [
      "Bekobod",
      "Bo'ka",
      "Chinoz",
      "Qibray",
      "Ohangaron",
      "Oqqo'rg'on",
      "Parkent",
      "Piskent",
      "Quyichirchiq",
      "O'rtachirchiq",
      "Yuqorichirchiq",
      "Toshkent tumani",
      "Yangiyo'l",
      "Zangiota",
    ],
  },
  {
    name: "Andijon viloyati",
    districts: [
      "Andijon shahri",
      "Andijon tumani",
      "Asaka",
      "Baliqchi",
      "Bo'z",
      "Buloqboshi",
      "Izboskan",
      "Jalaquduq",
      "Xo'jaobod",
      "Qo'rg'ontepa",
      "Marhamat",
      "Oltinko'l",
      "Paxtaobod",
      "Shahrixon",
      "Ulug'nor",
    ],
  },
  {
    name: "Farg'ona viloyati",
    districts: [
      "Farg'ona shahri",
      "Marg'ilon",
      "Qo'qon",
      "Farg'ona tumani",
      "Bag'dod",
      "Beshariq",
      "Buvayda",
      "Dang'ara",
      "Furqat",
      "Qo'shtepa",
      "Rishton",
      "So'x",
      "Toshloq",
      "O'zbekiston",
      "Uchko'prik",
      "Yozyovon",
    ],
  },
  {
    name: "Namangan viloyati",
    districts: [
      "Namangan shahri",
      "Chortoq",
      "Chust",
      "Kosonsoy",
      "Mingbuloq",
      "Namangan tumani",
      "Norin",
      "Pop",
      "To'raqo'rg'on",
      "Uychi",
      "Uchqo'rg'on",
      "Yangiqo'rg'on",
    ],
  },
  {
    name: "Samarqand viloyati",
    districts: [
      "Samarqand shahri",
      "Bulung'ur",
      "Ishtixon",
      "Jomboy",
      "Kattaqo'rg'on",
      "Narpay",
      "Nurobod",
      "Oqdaryo",
      "Pastdarg'om",
      "Payariq",
      "Paxtachi",
      "Samarqand tumani",
      "Toyloq",
      "Urgut",
    ],
  },
  {
    name: "Buxoro viloyati",
    districts: [
      "Buxoro shahri",
      "Buxoro tumani",
      "G'ijduvon",
      "Jondor",
      "Kogon",
      "Olot",
      "Peshku",
      "Qorako'l",
      "Qorovulbozor",
      "Romitan",
      "Shofirkon",
      "Vobkent",
    ],
  },
  {
    name: "Navoiy viloyati",
    districts: [
      "Navoiy shahri",
      "Konimex",
      "Karmana",
      "Navbahor",
      "Nurota",
      "Qiziltepa",
      "Tomdi",
      "Uchquduq",
      "Xatirchi",
    ],
  },
  {
    name: "Qashqadaryo viloyati",
    districts: [
      "Qarshi shahri",
      "Qarshi tumani",
      "Dehqonobod",
      "G'uzor",
      "Kasbi",
      "Kitob",
      "Koson",
      "Mirishkor",
      "Muborak",
      "Nishon",
      "Shahrisabz",
      "Yakkabog'",
      "Chiroqchi",
    ],
  },
  {
    name: "Surxondaryo viloyati",
    districts: [
      "Termiz shahri",
      "Angor",
      "Bandixon",
      "Boysun",
      "Denov",
      "Jarqo'rg'on",
      "Muzrabot",
      "Oltinsoy",
      "Qiziriq",
      "Qumqo'rg'on",
      "Sariosiyo",
      "Sherobod",
      "Sho'rchi",
      "Termiz tumani",
      "Uzun",
    ],
  },
  {
    name: "Jizzax viloyati",
    districts: [
      "Jizzax shahri",
      "Arnasoy",
      "Baxmal",
      "Do'stlik",
      "Forish",
      "G'allaorol",
      "Mirzacho'l",
      "Paxtakor",
      "Yangiobod",
      "Zafarobod",
      "Zarbdor",
      "Zomin",
    ],
  },
  {
    name: "Sirdaryo viloyati",
    districts: [
      "Guliston shahri",
      "Guliston tumani",
      "Boyovut",
      "Mirzaobod",
      "Oqoltin",
      "Sardoba",
      "Sayxunobod",
      "Sirdaryo",
      "Xovos",
    ],
  },
  {
    name: "Xorazm viloyati",
    districts: [
      "Urganch shahri",
      "Urganch tumani",
      "Bog'ot",
      "Gurlan",
      "Xazorasp",
      "Xonqa",
      "Qo'shko'pir",
      "Shovot",
      "Yangibozor",
      "Yangiariq",
    ],
  },
  {
    name: "Qoraqalpog'iston Respublikasi",
    districts: [
      "Nukus shahri",
      "Amudaryo",
      "Beruniy",
      "Chimboy",
      "Ellikqal'a",
      "Kegeyli",
      "Mo'ynoq",
      "Nukus tumani",
      "Qanliko'l",
      "Qorao'zak",
      "Qo'ng'irot",
      "Shumanay",
      "Taxtako'pir",
      "To'rtko'l",
      "Xo'jayli",
    ],
  },
];

export function getDistricts(regionName: string): string[] {
  return REGIONS.find((r) => r.name === regionName)?.districts ?? [];
}
